[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
etherscan_api_key = '${ETHERSCAN_API_KEY}'
solc_version= '0.8.16'

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
local = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
